defmodule FraytElixir.Test.FakeBringg do
  alias Phoenix.PubSub

  def get_merchant_creds(uuid) do
    {:ok,
     %HTTPoison.Response{
       status_code: 200,
       body:
         Jason.encode!(%{
           "merchant_name" => "random name",
           "merchant_uuid" => uuid,
           "api_endpoint" => "endpoint",
           "credentials" => %{
             "client_id" => "client_id",
             "client_secret" => "secret",
             "api_key" => "api_key"
           }
         })
     }}
  end

  def get_access_token("12345", "56789"),
    do:
      {:ok,
       %{
         "access_token" =>
           "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdXQiOiJvYXV0aDIiLCJqdGkiOiIwNDFjMzY5NTg2NTkyYmU1MDc3NjBiYTJhNDJhYjg3ZCIsInN1YiI6IlVzZXI6MTM5Nzc3NyIsInRpZCI6Ik1lcmNoYW50OjEzMjAiLCJpYXQiOjE2MDAzNzI1NjQsImV4cCI6MTYwMDM3NDM2NCwic2xpIjowLCJhdWQiOiI2VGpSdUdiek1NWUFSbGxaV3JJV3pZM2MwN2lSNDlfRlVMX3lfYWJWbElFIiwiaXNzIjoidXJuOngtYnJpbmdnOnNlcnZpY2U6YXBpIiwicmVnIjoidXMtZWFzdC00LWdjcCIsInNjcCI6WyJmbGVldCJdLCJ2ZXIiOiIyLjAifQ.GFExIvxE3mTKtG0gjEe4KVS6HDqHiRewPp_6sAgxcRXEAifHHKVwr6YTeS7FpoKYuIr5sEYV9ew9OBzhfBmtnQ",
         "created_at" => 1_600_372_564,
         "expires_in" => 1800,
         "token_type" => "Bearer"
       }}

  def get_access_token(_, _), do: {:error, "Invalid credentials"}

  def assign_driver(_, payload) do
    PubSub.broadcast!(FraytElixir.PubSub, "fake_bringg", {:bringg_assign_driver, payload})

    {:ok,
     %{
       "success" => true,
       "task" => %{
         "task_configuration_id" => nil,
         "automatically_cancelled" => 0,
         "late" => true,
         "extras" => nil,
         "price_before_tax" => nil,
         "title" => "Test order",
         "cancellation_lng" => nil,
         "way_points" => [
           %{
             "silent" => false,
             "etl" => "2020-09-11T18:22:57.801Z",
             "late" => true,
             "pickup_dropoff_option" => 0,
             "customer" => %{
               "confirmation_code" => "4517",
               "tax_payer_external_id" => nil,
               "original_phone_number" => nil,
               "extras" => nil,
               "dev" => false,
               "driver_preparation_time" => nil,
               "allow_login" => false,
               "consecutive_checkins_out_of_geofence" => 0,
               "phone" => nil,
               "client_version" => nil,
               "original_lat_lng_changed" => nil,
               "image" => nil,
               "client_name" => nil,
               "uuid" => "d8998d6e-3067-4961-914d-d3b8108aea15",
               "district" => nil,
               "id" => 11_557_430,
               "has_parking_area" => nil,
               "stripe_id" => nil,
               "external_id" => "11557430",
               "reset_password_token" => nil,
               "user_id" => nil,
               "original_lng" => nil,
               "street" => nil,
               "encrypted_password" => "",
               "delete_at" => nil,
               "tax_payer_name" => nil,
               "uploaded_profile_image" => %{"url" => "/images/avatar.png"},
               "address" => nil,
               "zipcode" => nil,
               "rank" => nil,
               "lat" => nil,
               "is_sales_rep" => false
             },
             "phone" => nil,
             "full_address" => "606 Taywood Rd, OH , USA, Englewood, 45322",
             "task_id" => 20_377_415,
             "company_name" => nil,
             "rating" => nil,
             "district" => nil,
             "id" => 27_750_916,
             "first_attempt_promise_no_later_than" => nil,
             "eta" => nil,
             "location_name" => nil,
             "checkout_lat" => nil,
             "customer_id" => 11_557_430,
             "address" => "606 Taywood Rd, OH , USA",
             "zipcode" => "45322",
             "no_earlier_than" => "2020-09-11T17:47:57.801Z",
             "lat" => 39.8656099,
             "note" => nil,
             "asap" => false,
             "checkout_lng" => nil,
             "done" => false,
             "borough" => nil,
             "ui_data" => nil,
             "scheduled_at" => "2020-09-11T18:17:57.801Z",
             "house_number" => nil,
             "checkin_lng" => nil,
             "name" => "Warehouse",
             "checkin_time" => nil,
             "city" => "Englewood",
             "no_later_than" => "2020-09-11T17:47:57.801Z",
             "address_second_line" => nil,
             "lng" => -84.2917405,
             "scheduled_arrival" => nil
           },
           %{
             "silent" => false,
             "etl" => "2020-09-11T19:22:57.801Z",
             "late" => false,
             "pickup_dropoff_option" => 1,
             "customer" => %{
               "confirmation_code" => "6998",
               "tax_payer_external_id" => nil,
               "original_phone_number" => "+12025550194",
               "extras" => nil,
               "dev" => false,
               "driver_preparation_time" => nil,
               "allow_login" => false,
               "consecutive_checkins_out_of_geofence" => 0,
               "phone" => "+12025550194",
               "client_version" => nil,
               "original_lat_lng_changed" => nil,
               "image" => nil,
               "client_name" => nil,
               "uuid" => "336261d3-9d9c-4006-992d-3b71cced89c2",
               "district" => nil,
               "id" => 11_557_429,
               "has_parking_area" => nil,
               "stripe_id" => nil,
               "external_id" => "11557429",
               "reset_password_token" => nil,
               "user_id" => nil,
               "original_lng" => nil,
               "street" => nil,
               "encrypted_password" => "",
               "delete_at" => nil,
               "tax_payer_name" => nil,
               "uploaded_profile_image" => %{"url" => "/images/avatar.png"},
               "address" => nil,
               "zipcode" => nil,
               "rank" => nil,
               "lat" => nil
             },
             "phone" => "+12025550194",
             "full_address" => "501 W National Rd, OH , USA, Englewood, 45322",
             "task_id" => 20_377_415,
             "company_name" => nil,
             "rating" => nil,
             "district" => nil,
             "id" => 27_750_917,
             "first_attempt_promise_no_later_than" => nil,
             "eta" => nil,
             "location_name" => nil,
             "checkout_lat" => nil,
             "customer_id" => 11_557_429,
             "address" => "501 W National Rd, OH , USA",
             "zipcode" => "45322",
             "no_earlier_than" => "2020-09-11T18:47:57.801Z",
             "lat" => 39.8774786,
             "note" => nil,
             "asap" => false,
             "checkout_lng" => nil,
             "done" => false,
             "borough" => nil,
             "ui_data" => nil,
             "scheduled_at" => "2020-09-11T19:17:57.801Z",
             "house_number" => nil,
             "checkin_lng" => nil,
             "name" => "Test Customer",
             "checkin_time" => nil,
             "city" => "Englewood",
             "no_later_than" => "2020-09-11T19:47:57.801Z",
             "address_second_line" => nil,
             "lng" => -84.3123227
           }
         ],
         "scans" => [],
         "task_inventories" => [
           %{
             "actions_configuration_id" => nil,
             "assigned_serial" => nil,
             "coc_type" => nil,
             "external_id" => "18419863",
             "height" => 100.0,
             "id" => 58_592_538,
             "image" => "/images/product-placeholder.png",
             "inventory" => %{
               "age_restricted" => nil,
               "commodity" => nil,
               "completed" => nil,
               "delivery_cost" => nil,
               "description" => nil,
               "external_id" => "18419863",
               "extras" => nil,
               "height" => 100.0,
               "id" => 18_419_863,
               "image" => "/images/product-placeholder.png",
               "length" => 50.0,
               "limitations" => nil,
               "merchant_id" => 1320,
               "name" => "Inventory",
               "notes" => nil,
               "price" => 20,
               "scan_string" => "7f54b00ef8edc6cd",
               "size" => nil,
               "volume" => nil,
               "weight" => 100.0,
               "width" => 50.0
             },
             "inventory_id" => 18_419_863,
             "length" => 50.0,
             "merchant_id" => 1320,
             "name" => "Inventory",
             "note" => nil,
             "original_quantity" => 1,
             "parent_task_inventory_id" => nil,
             "pending" => false,
             "price" => 20.0,
             "quantity" => 0,
             "rejected_quantity" => 0,
             "scan_string" => "7f54b00ef8edc6cd",
             "scheduled_arrival" => nil,
             "size" => nil,
             "source_task_id" => nil,
             "task_id" => 20_377_415,
             "way_point_id" => 27_750_917,
             "weight" => 100.0,
             "width" => 50.0
           },
           %{
             "actions_configuration_id" => nil,
             "assigned_serial" => nil,
             "coc_type" => nil,
             "external_id" => "18419863",
             "height" => 100.0,
             "id" => 58_592_537,
             "image" => "/images/product-placeholder.png",
             "inventory" => %{
               "age_restricted" => nil,
               "commodity" => nil,
               "completed" => nil,
               "delivery_cost" => nil,
               "description" => nil,
               "external_id" => "18419863",
               "extras" => nil,
               "height" => 100.0,
               "id" => 18_419_863,
               "image" => "/images/product-placeholder.png",
               "length" => 50.0,
               "limitations" => nil,
               "merchant_id" => 1320,
               "name" => "Inventory",
               "notes" => nil,
               "price" => 20,
               "scan_string" => "7f54b00ef8edc6cd",
               "size" => nil,
               "volume" => nil,
               "weight" => 100.0,
               "width" => 50.0
             },
             "inventory_id" => 18_419_863,
             "length" => 50.0,
             "merchant_id" => 1320,
             "name" => "Inventory",
             "note" => nil,
             "original_quantity" => 1,
             "parent_task_inventory_id" => nil,
             "pending" => true,
             "price" => 20.0,
             "quantity" => 0,
             "rejected_quantity" => 0,
             "scan_string" => "7f54b00ef8edc6cd",
             "scheduled_arrival" => nil,
             "size" => nil,
             "source_task_id" => nil,
             "task_id" => 20_377_415,
             "way_point_id" => 27_750_916,
             "weight" => 100.0,
             "width" => 50.0
           }
         ],
         "post_delivery_tip_credit" => nil,
         "fleet_delivery_external_id" => "abd574b7-3ac6-4b3d-80ee-e687dcf042df",
         "task_type_id" => nil,
         "origin_title" => nil,
         "uuid" => "b814329d-bdf8-478b-869b-bf4f051c79ce",
         "planning_published" => nil,
         "pre_delivery_tip" => nil,
         "tag_id" => nil,
         "total_price" => 100.0,
         "id" => 20_377_415,
         "preparation_status" => 0,
         "ended_time" => nil,
         "external_id" => "561e1a26",
         "delivery_price" => 50.0,
         "user_id" => 1_451_061,
         "tip" => nil,
         "task_notes" => [],
         "group_leader_id" => nil,
         "task_cancellation_reason" => nil,
         "customer_id" => 11_557_429,
         "address" => "606 Taywood Rd, OH , USA",
         "payment_method" => 1,
         "rank" => nil,
         "cancellation_lat" => nil,
         "lat" => 39.8656099,
         "preparation_start_time_planned" => nil,
         "parent_task_id" => nil,
         "cancelled_at" => nil,
         "ready_to_execute" => true,
         "delivery_cost" => nil,
         "asap" => false,
         "scheduled_at" => "2020-09-11T18:17:57.801Z",
         "virtual_task" => false,
         "status" => 6,
         "linked_task_id" => nil,
         "tax_price" => nil
       }
     }}
  end

  def start_order(_, payload) do
    PubSub.broadcast!(FraytElixir.PubSub, "fake_bringg", {:start_order, payload})

    {:ok,
     %{
       "success" => true,
       "task" => %{
         "late" => true,
         "customer" => %{
           "address" => nil,
           "address_second_line" => nil,
           "allow_login" => false,
           "borough" => nil,
           "business_code" => nil,
           "city" => nil,
           "client_name" => nil,
           "client_version" => nil,
           "confirmation_code" => "9420",
           "customer_notes" => [],
           "email" => "test@bringg.com",
           "external_id" => "11869174",
           "extras" => nil,
           "has_parking_area" => nil,
           "id" => 11_869_174,
           "image" => "/images/avatar.png",
           "language" => nil,
           "lat" => nil,
           "lng" => nil,
           "merchant_id" => 1320,
           "mobile_type" => 0,
           "name" => "Test Customer",
           "phone" => "+12025550194",
           "rank" => nil,
           "state" => nil,
           "street" => nil,
           "team_ids" => [],
           "zipcode" => nil
         },
         "extras" => nil,
         "title" => "Test order",
         "way_points" => [
           %{
             "silent" => false,
             "etl" => "2020-09-18T19:44:45.500Z",
             "late" => true,
             "customer" => %{
               "address" => nil,
               "address_second_line" => nil,
               "allow_login" => false,
               "borough" => nil,
               "business_code" => nil,
               "city" => nil,
               "client_name" => nil,
               "client_version" => nil,
               "confirmation_code" => "2687",
               "customer_notes" => [],
               "email" => "",
               "external_id" => "11869178",
               "extras" => nil,
               "has_parking_area" => nil,
               "id" => 11_869_178,
               "image" => "/images/avatar.png",
               "language" => nil,
               "lat" => nil,
               "lng" => nil,
               "merchant_id" => 1320,
               "mobile_type" => 0,
               "name" => "Warehouse",
               "phone" => nil,
               "rank" => nil,
               "state" => nil,
               "street" => nil,
               "team_ids" => [],
               "zipcode" => nil
             },
             "allow_editing_inventory" => true,
             "inventory_changes" => [],
             "phone" => nil,
             "task_id" => 21_695_571,
             "rating" => nil,
             "id" => 29_350_457,
             "contacts" => [],
             "eta" => nil,
             "location_name" => nil,
             "street" => nil,
             "customer_id" => 11_869_178,
             "address" => "1415 Old Springfield Rd, OH , USA",
             "zipcode" => "45377",
             "no_earlier_than" => "2020-09-18T19:09:45.500Z",
             "lat" => 39.91412,
             "note" => nil,
             "allow_scanning_inventory" => true,
             "must_approve_inventory" => false,
             "allow_editing_payment" => nil,
             "distance_traveled_server" => nil,
             "asap" => false,
             "done" => false,
             "borough" => nil,
             "ui_data" => nil,
             "scheduled_at" => "2020-09-18T19:39:45.500Z",
             "name" => "Warehouse",
             "checkin_time" => nil,
             "extra_customers" => [],
             "city" => "Vandalia",
             "no_later_than" => "2020-09-18T19:09:45.500Z",
             "address_second_line" => nil,
             "lng" => -84.266757,
             "automatic_checkin" => nil,
             "position" => 1,
             "pending_geocode" => false,
             "has_to_leave_by" => nil
           },
           %{
             "silent" => false,
             "etl" => "2020-09-18T20:44:45.500Z",
             "late" => false,
             "customer" => %{
               "address" => nil,
               "address_second_line" => nil,
               "allow_login" => false,
               "borough" => nil,
               "business_code" => nil,
               "city" => nil,
               "client_name" => nil,
               "client_version" => nil,
               "confirmation_code" => "9420",
               "customer_notes" => [],
               "email" => "test@bringg.com",
               "external_id" => "11869174",
               "extras" => nil,
               "has_parking_area" => nil,
               "id" => 11_869_174,
               "image" => "/images/avatar.png",
               "language" => nil,
               "lat" => nil,
               "lng" => nil,
               "merchant_id" => 1320,
               "mobile_type" => 0,
               "name" => "Test Customer",
               "phone" => "+12025550194",
               "rank" => nil,
               "state" => nil,
               "street" => nil,
               "team_ids" => [],
               "zipcode" => nil
             },
             "allow_editing_inventory" => true,
             "inventory_changes" => [],
             "phone" => "+12025550194",
             "task_id" => 21_695_571,
             "rating" => nil,
             "id" => 29_350_458,
             "contacts" => [
               %{
                 "contact_type" => "phone",
                 "contact_value" => "+12025550194",
                 "customer_id" => 11_869_174,
                 "opted_by_customer" => false,
                 "sharing_allowed" => true
               },
               %{
                 "contact_type" => "email",
                 "contact_value" => "test@bringg.com",
                 "customer_id" => 11_869_174,
                 "opted_by_customer" => false,
                 "sharing_allowed" => true
               }
             ],
             "eta" => nil,
             "location_name" => nil,
             "street" => nil,
             "customer_id" => 11_869_174,
             "address" => "410 W National Rd, OH , USA",
             "zipcode" => "45322",
             "no_earlier_than" => "2020-09-18T20:09:45.500Z",
             "lat" => 39.8765494,
             "note" => nil,
             "allow_scanning_inventory" => true,
             "must_approve_inventory" => false,
             "allow_editing_payment" => nil,
             "distance_traveled_server" => nil,
             "asap" => false,
             "done" => false,
             "borough" => nil,
             "ui_data" => nil,
             "scheduled_at" => "2020-09-18T20:39:45.500Z",
             "name" => "Test Customer",
             "checkin_time" => nil,
             "extra_customers" => [],
             "city" => "Englewood",
             "no_later_than" => "2020-09-18T21:09:45.500Z",
             "address_second_line" => nil,
             "lng" => -84.3103292,
             "automatic_checkin" => nil,
             "position" => 2,
             "pending_geocode" => false
           }
         ],
         "scans" => [],
         "task_inventories" => [
           %{
             "actions_configuration_id" => nil,
             "assigned_serial" => nil,
             "coc_type" => nil,
             "external_id" => "18586317",
             "height" => 100.0,
             "id" => 61_001_088,
             "image" => "/images/product-placeholder.png",
             "inventory" => %{
               "age_restricted" => nil,
               "commodity" => nil,
               "completed" => nil,
               "delivery_cost" => nil,
               "description" => nil,
               "external_id" => "18586317",
               "extras" => nil,
               "height" => 100.0,
               "id" => 18_586_317,
               "image" => "/images/product-placeholder.png",
               "length" => 50.0,
               "limitations" => nil,
               "merchant_id" => 1320,
               "name" => "Inventory",
               "notes" => nil,
               "price" => 20,
               "scan_string" => "f323d03b178d1159",
               "size" => nil,
               "volume" => nil,
               "weight" => 100.0,
               "width" => 50.0
             },
             "inventory_id" => 18_586_317,
             "length" => 50.0,
             "merchant_id" => 1320,
             "name" => "Inventory",
             "note" => nil,
             "original_quantity" => 1,
             "parent_task_inventory_id" => nil,
             "pending" => false,
             "price" => 20.0,
             "quantity" => 0,
             "rejected_quantity" => 0,
             "scan_string" => "f323d03b178d1159",
             "scheduled_arrival" => nil,
             "size" => nil,
             "source_task_id" => nil,
             "task_id" => 21_695_571,
             "way_point_id" => 29_350_458,
             "weight" => 100.0,
             "width" => 50.0
           },
           %{
             "actions_configuration_id" => nil,
             "assigned_serial" => nil,
             "coc_type" => nil,
             "external_id" => "18586317",
             "height" => 100.0,
             "id" => 61_001_083,
             "image" => "/images/product-placeholder.png",
             "inventory" => %{
               "age_restricted" => nil,
               "commodity" => nil,
               "completed" => nil,
               "delivery_cost" => nil,
               "description" => nil,
               "external_id" => "18586317",
               "extras" => nil,
               "height" => 100.0,
               "id" => 18_586_317,
               "image" => "/images/product-placeholder.png",
               "length" => 50.0,
               "limitations" => nil,
               "merchant_id" => 1320,
               "name" => "Inventory",
               "notes" => nil,
               "price" => 20,
               "scan_string" => "f323d03b178d1159",
               "size" => nil,
               "volume" => nil,
               "weight" => 100.0,
               "width" => 50.0
             },
             "inventory_id" => 18_586_317,
             "length" => 50.0,
             "merchant_id" => 1320,
             "name" => "Inventory",
             "note" => nil,
             "original_quantity" => 1,
             "parent_task_inventory_id" => nil,
             "pending" => true,
             "price" => 20.0,
             "quantity" => 0,
             "rejected_quantity" => 0,
             "scan_string" => "f323d03b178d1159",
             "scheduled_arrival" => nil,
             "size" => nil,
             "source_task_id" => nil,
             "task_id" => 21_695_571,
             "way_point_id" => 29_350_457,
             "weight" => 100.0,
             "width" => 50.0
           }
         ],
         "fleet_delivery_external_id" => "1383f1d5-fea4-47cc-81b2-1574911b99c0",
         "origin_title" => nil,
         "uuid" => "94b1191a-b1db-4990-83f1-9e10e5f87829",
         "tag_id" => nil,
         "total_price" => 100.0,
         "id" => 21_695_571,
         "first_way_point_has_to_leave_by" => nil,
         "scheduled_to_be_ready" => nil,
         "late_reason" => nil,
         "external_id" => "b0c3e637",
         "delivery_price" => 50.0,
         "user_id" => 1_459_358,
         "run_start_time" => "2020-09-18T21:58:04.679Z",
         "task_notes" => [],
         "user" => %{
           "estimated_last_etl" => nil,
           "dispatcher" => false,
           "customer" => false,
           "home_lng" => nil,
           "home_lat" => nil,
           "company" => nil,
           "phone" => nil,
           "authorization_flags" => %{
             "access_user" => %{"access_to_all_users" => true},
             "customer_care" => %{"value" => true},
             "customers_menu" => %{"value" => true},
             "cancel_task" => %{"value" => true},
             "acknowledge" => %{"value" => true},
             "access_task" => %{"access_to_all_tasks" => true},
             "dispatch" => %{"value" => true},
             "drivers" => %{"value" => true},
             "add_driver" => %{"value" => true},
             "assign_user_to_company" => %{"value" => false},
             "enable_setting_page" => %{"value" => false},
             "user_types" => %{"value" => true},
             "dashboard" => %{"value" => true},
             "cashout_edit_distance" => %{"value" => true},
             "enable_merchant_logs" => %{"value" => false}
           },
           "locked" => false,
           "estimated_last_lat" => nil,
           "private_vehicle" => true,
           "profile_image" => "/images/avatar.png",
           "uuid" => "18d0f2fd-a694-4d08-8919-985df409a497",
           "driver" => true,
           "default_user_activity" => 5,
           "average_rating" => nil,
           "id" => 1_459_358,
           "os_version" => nil,
           "estimated_last_lng" => nil,
           "external_id" => "b2e16417-4e0b-4fbe-a7ce-ee59d0c3ebfa",
           "default_welcome_url_id" => nil,
           "vehicle_skills" => [],
           "original_user_id" => nil,
           "at_home" => false
         },
         "address" => "1415 Old Springfield Rd, OH , USA",
         "lat" => 39.91412,
         "cancelled_at" => nil,
         "asap" => false,
         "scheduled_at" => "2020-09-18T19:39:45.500Z",
         "run_end_time" => nil,
         "status" => 2,
         "merchant_name" => nil,
         "linked_task_id" => nil,
         "tip_driver_enabled" => false,
         "discount" => nil,
         "created_at" => "2020-09-18T18:39:45.578Z",
         "priority" => 21_695_571,
         "run_uuid" => "29ca3822-e3ef-4a6b-a4ee-abdc6f9d9dc4",
         "payment_type_name" => nil,
         "distance_traveled" => nil,
         "active_way_point_id" => 29_350_457,
         "left_to_be_paid" => nil,
         "lng" => -84.266757,
         "dispatcher_id" => nil,
         "started_time" => "2020-09-18T21:58:04.679Z",
         "fleet_id" => 273,
         "team_ids" => [97472],
         "shared_locations" => []
       }
     }}
  end

  def check_in(_, payload) do
    PubSub.broadcast!(FraytElixir.PubSub, "fake_bringg", {:check_in, payload})

    {:ok,
     %{
       "success" => true,
       "task" => %{
         "task_configuration_id" => nil,
         "automatically_cancelled" => 0,
         "late" => true,
         "extras" => nil,
         "price_before_tax" => nil,
         "title" => "Test order",
         "cancellation_lng" => nil,
         "way_points" => [
           %{
             "silent" => false,
             "etl" => "2020-09-22T20:50:00.083Z",
             "late" => true,
             "pickup_dropoff_option" => 0,
             "customer" => %{
               "confirmation_code" => "4517",
               "tax_payer_external_id" => nil,
               "original_phone_number" => nil,
               "extras" => nil,
               "dev" => false,
               "driver_preparation_time" => nil,
               "allow_login" => false,
               "consecutive_checkins_out_of_geofence" => 0,
               "phone" => nil,
               "client_version" => nil,
               "original_lat_lng_changed" => nil,
               "image" => nil,
               "client_name" => nil,
               "uuid" => "d8998d6e-3067-4961-914d-d3b8108aea15",
               "district" => nil,
               "id" => 11_557_430,
               "has_parking_area" => nil,
               "stripe_id" => nil,
               "external_id" => "11557430",
               "reset_password_token" => nil,
               "user_id" => nil,
               "original_lng" => nil,
               "street" => nil,
               "encrypted_password" => "",
               "delete_at" => nil,
               "tax_payer_name" => nil,
               "uploaded_profile_image" => %{"url" => "/images/avatar.png"},
               "address" => nil,
               "zipcode" => nil,
               "rank" => nil,
               "lat" => nil,
               "is_sales_rep" => false
             },
             "phone" => nil,
             "full_address" => "606 Taywood Rd, OH , USA, Englewood, 45322",
             "task_id" => 20_377_415,
             "company_name" => nil,
             "rating" => nil,
             "district" => nil,
             "id" => 27_750_916,
             "first_attempt_promise_no_later_than" => nil,
             "eta" => nil,
             "location_name" => nil,
             "checkout_lat" => nil,
             "customer_id" => 11_557_430,
             "address" => "606 Taywood Rd, OH , USA",
             "zipcode" => "45322",
             "no_earlier_than" => "2020-09-11T17:47:57.801Z",
             "lat" => 39.8656099,
             "note" => nil,
             "asap" => false,
             "checkout_lng" => nil,
             "done" => false,
             "borough" => nil,
             "ui_data" => nil,
             "scheduled_at" => "2020-09-11T18:17:57.801Z",
             "house_number" => nil,
             "checkin_lng" => -84.5101958,
             "name" => "Warehouse",
             "checkin_time" => "2020-09-22T20:45:00.083Z",
             "city" => "Englewood",
             "no_later_than" => "2020-09-11T17:47:57.801Z",
             "address_second_line" => nil,
             "lng" => -84.2917405,
             "scheduled_arrival" => nil
           },
           %{
             "silent" => false,
             "etl" => "2020-09-11T19:22:57.801Z",
             "late" => false,
             "pickup_dropoff_option" => 1,
             "customer" => %{
               "confirmation_code" => "6998",
               "tax_payer_external_id" => nil,
               "original_phone_number" => "+12025550194",
               "extras" => nil,
               "dev" => false,
               "driver_preparation_time" => nil,
               "allow_login" => false,
               "consecutive_checkins_out_of_geofence" => 0,
               "phone" => "+12025550194",
               "client_version" => nil,
               "original_lat_lng_changed" => nil,
               "image" => nil,
               "client_name" => nil,
               "uuid" => "336261d3-9d9c-4006-992d-3b71cced89c2",
               "district" => nil,
               "id" => 11_557_429,
               "has_parking_area" => nil,
               "stripe_id" => nil,
               "external_id" => "11557429",
               "reset_password_token" => nil,
               "user_id" => nil,
               "original_lng" => nil,
               "street" => nil,
               "encrypted_password" => "",
               "delete_at" => nil,
               "tax_payer_name" => nil,
               "uploaded_profile_image" => %{"url" => "/images/avatar.png"},
               "address" => nil,
               "zipcode" => nil,
               "rank" => nil,
               "lat" => nil
             },
             "phone" => "+12025550194",
             "full_address" => "501 W National Rd, OH , USA, Englewood, 45322",
             "task_id" => 20_377_415,
             "company_name" => nil,
             "rating" => nil,
             "district" => nil,
             "id" => 27_750_917,
             "first_attempt_promise_no_later_than" => nil,
             "eta" => nil,
             "location_name" => nil,
             "checkout_lat" => nil,
             "customer_id" => 11_557_429,
             "address" => "501 W National Rd, OH , USA",
             "zipcode" => "45322",
             "no_earlier_than" => "2020-09-11T18:47:57.801Z",
             "lat" => 39.8774786,
             "note" => nil,
             "asap" => false,
             "checkout_lng" => nil,
             "done" => false,
             "borough" => nil,
             "ui_data" => nil,
             "scheduled_at" => "2020-09-11T19:17:57.801Z",
             "house_number" => nil,
             "checkin_lng" => nil,
             "name" => "Test Customer",
             "checkin_time" => nil,
             "city" => "Englewood",
             "no_later_than" => "2020-09-11T19:47:57.801Z",
             "address_second_line" => nil,
             "lng" => -84.3123227
           }
         ],
         "scans" => [],
         "task_inventories" => [
           %{
             "actions_configuration_id" => nil,
             "assigned_serial" => nil,
             "coc_type" => nil,
             "external_id" => "18419863",
             "height" => 100.0,
             "id" => 58_592_538,
             "image" => "/images/product-placeholder.png",
             "inventory" => %{
               "age_restricted" => nil,
               "commodity" => nil,
               "completed" => nil,
               "delivery_cost" => nil,
               "description" => nil,
               "external_id" => "18419863",
               "extras" => nil,
               "height" => 100.0,
               "id" => 18_419_863,
               "image" => "/images/product-placeholder.png",
               "length" => 50.0,
               "limitations" => nil,
               "merchant_id" => 1320,
               "name" => "Inventory",
               "notes" => nil,
               "price" => 20,
               "scan_string" => "7f54b00ef8edc6cd",
               "size" => nil,
               "volume" => nil,
               "weight" => 100.0,
               "width" => 50.0
             },
             "inventory_id" => 18_419_863,
             "length" => 50.0,
             "merchant_id" => 1320,
             "name" => "Inventory",
             "note" => nil,
             "original_quantity" => 1,
             "parent_task_inventory_id" => nil,
             "pending" => false,
             "price" => 20.0,
             "quantity" => 0,
             "rejected_quantity" => 0,
             "scan_string" => "7f54b00ef8edc6cd",
             "scheduled_arrival" => nil,
             "size" => nil,
             "source_task_id" => nil,
             "task_id" => 20_377_415,
             "way_point_id" => 27_750_917,
             "weight" => 100.0,
             "width" => 50.0
           },
           %{
             "actions_configuration_id" => nil,
             "assigned_serial" => nil,
             "coc_type" => nil,
             "external_id" => "18419863",
             "height" => 100.0,
             "id" => 58_592_537,
             "image" => "/images/product-placeholder.png",
             "inventory" => %{
               "age_restricted" => nil,
               "commodity" => nil,
               "completed" => nil,
               "delivery_cost" => nil,
               "description" => nil,
               "external_id" => "18419863",
               "extras" => nil,
               "height" => 100.0,
               "id" => 18_419_863,
               "image" => "/images/product-placeholder.png",
               "length" => 50.0,
               "limitations" => nil,
               "merchant_id" => 1320,
               "name" => "Inventory",
               "notes" => nil,
               "price" => 20,
               "scan_string" => "7f54b00ef8edc6cd",
               "size" => nil,
               "volume" => nil,
               "weight" => 100.0,
               "width" => 50.0
             },
             "inventory_id" => 18_419_863,
             "length" => 50.0,
             "merchant_id" => 1320,
             "name" => "Inventory",
             "note" => nil,
             "original_quantity" => 1,
             "parent_task_inventory_id" => nil,
             "pending" => true,
             "price" => 20.0,
             "quantity" => 0,
             "rejected_quantity" => 0,
             "scan_string" => "7f54b00ef8edc6cd",
             "scheduled_arrival" => nil,
             "size" => nil,
             "source_task_id" => nil,
             "task_id" => 20_377_415,
             "way_point_id" => 27_750_916,
             "weight" => 100.0,
             "width" => 50.0
           }
         ],
         "post_delivery_tip_credit" => nil,
         "fleet_delivery_external_id" => "abd574b7-3ac6-4b3d-80ee-e687dcf042df",
         "task_type_id" => nil,
         "origin_title" => nil,
         "uuid" => "b814329d-bdf8-478b-869b-bf4f051c79ce",
         "planning_published" => nil,
         "pre_delivery_tip" => nil,
         "tag_id" => nil,
         "total_price" => 100.0,
         "id" => 20_377_415,
         "preparation_status" => 0,
         "ended_time" => nil,
         "external_id" => "561e1a26",
         "delivery_price" => 50.0,
         "user_id" => 1_451_061,
         "tip" => nil,
         "task_notes" => [],
         "group_leader_id" => nil,
         "task_cancellation_reason" => nil,
         "customer_id" => 11_557_429,
         "address" => "606 Taywood Rd, OH , USA",
         "payment_method" => 1,
         "rank" => nil,
         "cancellation_lat" => nil,
         "lat" => 39.8656099,
         "preparation_start_time_planned" => nil,
         "parent_task_id" => nil,
         "cancelled_at" => nil,
         "ready_to_execute" => true,
         "delivery_cost" => nil,
         "asap" => false,
         "scheduled_at" => "2020-09-11T18:17:57.801Z",
         "virtual_task" => false,
         "status" => 3,
         "linked_task_id" => nil,
         "tax_price" => nil
       }
     }}
  end

  def update_driver_location(_, payload) do
    PubSub.broadcast!(FraytElixir.PubSub, "fake_bringg", {:update_driver_location, payload})

    {:ok, %{"rc" => 0, "success" => true}}
  end

  def create_note(_, payload) do
    PubSub.broadcast!(FraytElixir.PubSub, "fake_bringg", {:create_note, payload})

    {:ok,
     %{
       "success" => true,
       "task_signature" => %{
         "author_name" => "Frayt",
         "created_at" => "2020-09-22T20:06:32.569Z",
         "id" => 23_145_207,
         "task_id" => 21_695_571,
         "task_inventory_id" => nil,
         "title" => "22 Sep, 2020 08:06 PM, Frayt",
         "url" => "/deault_customer_avatar.jpg",
         "way_point_id" => 29_350_458
       }
     }}
  end

  def check_out(_, payload) do
    PubSub.broadcast!(FraytElixir.PubSub, "fake_bringg", {:check_out, payload})

    {:ok,
     %{
       "success" => true,
       "task" => %{
         "title" => "1591098207",
         "user_id" => 669_602,
         "created_at" => "2020-06-02T11:43:28.866Z",
         "scheduled_at" => nil,
         "lat" => 35.6961331,
         "lng" => -78.6922998,
         "status" => 2,
         "id" => 7_188_943,
         "address" => "6305 LAKE WHEELER RD",
         "active_way_point_id" => 11_061_565,
         "started_time" => "2020-06-03T16:59:43.351Z",
         "cancelled_at" => nil,
         "cancellation_lat" => nil,
         "cancellation_lng" => nil,
         "late" => false,
         "extras" => %{
           "integration" => %{
             "trackingNumber" => "1591098207",
             "uniqueIdentifier" => "ABC"
           }
         },
         "external_id" => "1591098207-R0",
         "customer_id" => 7_199_889,
         "asap" => nil,
         "ended_time" => nil,
         "priority" => 7_188_943,
         "distance_traveled" => nil,
         "total_price" => nil,
         "delivery_cost" => nil,
         "delivery_price" => nil,
         "tip" => nil,
         "pre_delivery_tip" => nil,
         "post_delivery_tip_cash" => nil,
         "post_delivery_tip_credit" => nil,
         "left_to_be_paid" => nil,
         "task_cancellation_reason" => nil,
         "dispatcher_id" => nil,
         "uuid" => "c3952fcd-80ba-4e31-b1cd-bf861e2b0503",
         "ready_to_execute" => true,
         "discount" => nil,
         "tip_driver_enabled" => false,
         "tax_price" => nil,
         "price_before_tax" => nil,
         "tag_id" => 588,
         "group_uuid" => nil,
         "group_leader_id" => nil,
         "automatically_cancelled" => 0,
         "parent_task_id" => nil,
         "payment_method" => nil,
         "payment_type_name" => nil,
         "linked_task_id" => nil,
         "preparation_status" => 0,
         "preparation_start_time_planned" => nil,
         "preparation_end_time_planned" => nil,
         "preparation_ready_for_pickup_time_planned" => nil,
         "invalidated" => false,
         "automatically_assigned" => true,
         "task_type_id" => 4,
         "origin_title" => "Service",
         "task_configuration_id" => nil,
         "required_skills" => [],
         "team_ids" => [
           77910
         ],
         "virtual_task" => false,
         "run_id" => 3_491_474,
         "fleet_id" => 180,
         "preparation_external_id" => nil,
         "rank" => nil,
         "fleet_delivery_external_id" => "123",
         "task_notes" => [],
         "way_points" => [
           %{
             "id" => 11_061_564,
             "scheduled_at" => nil,
             "has_to_leave_by" => nil,
             "task_id" => 7_188_943,
             "customer_id" => 7_199_890,
             "done" => true,
             "lat" => 35.7686299,
             "lng" => -78.5487832,
             "address" => "5210 TRADEMARK DRIVE, RALEIGH, NC",
             "address_second_line" => nil,
             "zipcode" => "27610",
             "position" => 1,
             "checkin_time" => "2020-06-03T17:15:29.697Z",
             "checkout_time" => "2020-06-03T17:21:05.987Z",
             "note" => nil,
             "find_me" => nil,
             "asap" => nil,
             "late" => false,
             "etl" => "2020-06-03T17:21:05.987Z",
             "eta" => nil,
             "silent" => false,
             "city" => "Raleigh",
             "borough" => nil,
             "full_address" => "5210 TRADEMARK DRIVE, RALEIGH, NC, Raleigh, 27610",
             "automatic_checkin" => false,
             "automatic_checkout" => false,
             "phone" => nil,
             "email" => nil,
             "no_later_than" => nil,
             "no_earlier_than" => nil,
             "rating" => nil,
             "checkin_lat" => nil,
             "checkin_lng" => nil,
             "checkout_lat" => nil,
             "checkout_lng" => nil,
             "district" => nil,
             "house_number" => nil,
             "company_name" => nil,
             "pickup_dropoff_option" => 0,
             "etos" => 300,
             "address_type" => nil,
             "location_name" => nil,
             "scheduled_arrival" => nil,
             "name" => "Warehouse",
             "ui_data" => nil,
             "customer" => %{
               "id" => 7_199_890,
               "name" => "Warehouse",
               "address" => nil,
               "lat" => nil,
               "lng" => nil,
               "created_at" => "2020-06-02T11:43:28.443Z",
               "updated_at" => "2020-06-03T17:15:29.938Z",
               "phone" => nil,
               "merchant_id" => 1007,
               "image" => nil,
               "access_token" => "e9e6cc96-d195-4b6a-a14b-767f40266880",
               "confirmation_code" => "1078",
               "salt" => nil,
               "approved" => false,
               "push_token" => nil,
               "uuid" => "4dfac88e-2ae2-4c38-95ee-edebde81746d",
               "email" => nil,
               "external_id" => "7199890",
               "delete_at" => nil,
               "facebook_id" => nil,
               "extras" => nil,
               "original_lat_lng_changed" => nil,
               "encrypted_password" => "",
               "blocked_email" => false,
               "address_second_line" => nil,
               "zipcode" => nil,
               "allow_login" => false,
               "stripe_id" => nil,
               "original_phone_number" => nil,
               "last_open_at" => nil,
               "last_order_at" => nil,
               "uploaded_profile_image" => %{
                 "url" => "/images/avatar.png"
               },
               "original_lat" => nil,
               "original_lng" => nil,
               "consecutive_checkins_out_of_geofence" => 0,
               "allow_sending_email" => true,
               "allow_sending_sms" => true,
               "reset_password_token" => nil,
               "reset_password_sent_at" => nil,
               "mobile_version" => nil,
               "mobile_type" => 0,
               "mobile_maker" => nil,
               "client_version" => nil,
               "client_name" => nil,
               "city" => nil,
               "borough" => nil,
               "state" => nil,
               "dev" => false,
               "business_code" => nil,
               "language" => nil,
               "district" => nil,
               "house_number" => nil,
               "street" => nil,
               "allow_dynamically_updating_location" => nil,
               "is_sales_rep" => false,
               "address_type" => nil,
               "tax_payer_external_id" => nil,
               "tax_payer_name" => nil,
               "rank" => nil,
               "user_id" => nil
             }
           },
           %{
             "id" => 11_061_565,
             "scheduled_at" => nil,
             "has_to_leave_by" => nil,
             "task_id" => 7_188_943,
             "customer_id" => 7_199_049,
             "done" => false,
             "lat" => 35.6961331,
             "lng" => -78.6922998,
             "address" => "6305 LAKE WHEELER RD",
             "address_second_line" => nil,
             "zipcode" => "27603",
             "position" => 2,
             "checkin_time" => nil,
             "checkout_time" => nil,
             "note" => nil,
             "find_me" => nil,
             "asap" => nil,
             "late" => false,
             "etl" => "2020-06-03T17:23:57.866Z",
             "eta" => "2020-06-03T17:18:57.866Z",
             "silent" => false,
             "city" => "RALEIGH",
             "borough" => nil,
             "full_address" => "6305 LAKE WHEELER RD, RALEIGH, NC, 27603",
             "automatic_checkin" => false,
             "automatic_checkout" => false,
             "phone" => "+15555555555",
             "email" => "",
             "no_later_than" => nil,
             "no_earlier_than" => nil,
             "rating" => nil,
             "checkin_lat" => nil,
             "checkin_lng" => nil,
             "checkout_lat" => nil,
             "checkout_lng" => nil,
             "district" => nil,
             "house_number" => nil,
             "company_name" => nil,
             "pickup_dropoff_option" => 1,
             "etos" => 300,
             "address_type" => nil,
             "location_name" => nil,
             "scheduled_arrival" => nil,
             "name" => "DO SUPPLY INC",
             "ui_data" => nil,
             "customer" => %{
               "id" => 7_199_049,
               "name" => "John Smith",
               "address" => nil,
               "lat" => nil,
               "lng" => nil,
               "created_at" => "2020-06-02T08:01:47.114Z",
               "updated_at" => "2020-06-02T08:47:06.584Z",
               "phone" => "+15555555555",
               "merchant_id" => 1007,
               "image" => nil,
               "access_token" => "767305d7-4eac-43fb-b731-6028f9f1d41b",
               "confirmation_code" => "1543",
               "salt" => nil,
               "approved" => false,
               "push_token" => nil,
               "uuid" => "0846443f-abcf-4a36-b033-387da774be06",
               "email" => "",
               "external_id" => "7199049",
               "delete_at" => nil,
               "facebook_id" => nil,
               "extras" => nil,
               "original_lat_lng_changed" => nil,
               "encrypted_password" => "",
               "blocked_email" => false,
               "address_second_line" => nil,
               "zipcode" => nil,
               "allow_login" => false,
               "stripe_id" => nil,
               "original_phone_number" => "+15555555555",
               "last_open_at" => nil,
               "last_order_at" => nil,
               "uploaded_profile_image" => %{
                 "url" => "/images/avatar.png"
               },
               "original_lat" => nil,
               "original_lng" => nil,
               "consecutive_checkins_out_of_geofence" => 0,
               "allow_sending_email" => true,
               "allow_sending_sms" => true,
               "reset_password_token" => nil,
               "reset_password_sent_at" => nil,
               "mobile_version" => nil,
               "mobile_type" => 0,
               "mobile_maker" => nil,
               "client_version" => nil,
               "client_name" => nil,
               "city" => nil,
               "borough" => nil,
               "state" => nil,
               "dev" => false,
               "business_code" => nil,
               "language" => nil,
               "district" => nil,
               "house_number" => nil,
               "street" => nil,
               "allow_dynamically_updating_location" => nil,
               "is_sales_rep" => false,
               "address_type" => nil,
               "tax_payer_external_id" => nil,
               "tax_payer_name" => nil,
               "rank" => nil,
               "user_id" => nil
             }
           }
         ],
         "shared_locations" => [
           %{
             "id" => 7_994_142,
             "url" => "https://app.bringg.com/sen.html?e8oPy81V&e=6",
             "expired" => false,
             "way_point_id" => 11_061_565,
             "customer_id" => 7_199_049,
             "first_seen_on" => nil,
             "failure_reason" => nil,
             "shared_successfully" => true,
             "shared_on" => "2020-06-03T17:21:07.169Z",
             "view_counter" => 0,
             "uuid" => "e8oPy81V",
             "sharing_method" => 0,
             "shared_type" => 1,
             "was_forwarded" => false
           }
         ],
         "task_inventories" => [
           %{
             "id" => 29_417_962,
             "task_id" => 7_188_943,
             "inventory_id" => 14_323_336,
             "quantity" => 0,
             "original_quantity" => 1,
             "merchant_id" => 1007,
             "name" => "MODULES",
             "price" => nil,
             "image" => "/images/product-placeholder.png",
             "way_point_id" => 11_061_565,
             "scan_string" => "1591098207",
             "pending" => false,
             "note" => "Other",
             "parent_task_inventory_id" => nil,
             "coc_type" => nil,
             "external_id" => "14323336",
             "size" => nil,
             "weight" => 450.0,
             "length" => nil,
             "height" => nil,
             "width" => nil,
             "source_task_id" => nil,
             "rejected_quantity" => 0,
             "assigned_serial" => nil,
             "actions_configuration_id" => nil,
             "scheduled_arrival" => nil,
             "inventory" => %{
               "id" => 14_323_336,
               "name" => "MODULES",
               "price" => 20,
               "image" => "/images/product-placeholder.png",
               "merchant_id" => 1007,
               "external_id" => "14323336",
               "scan_string" => "1591098207",
               "commodity" => nil,
               "notes" => nil,
               "weight" => 450.0,
               "size" => nil,
               "extras" => nil,
               "delivery_cost" => nil,
               "completed" => nil,
               "width" => nil,
               "height" => nil,
               "length" => nil,
               "volume" => nil,
               "description" => nil,
               "limitations" => nil,
               "age_restricted" => nil
             }
           },
           %{
             "id" => 29_417_961,
             "task_id" => 7_188_943,
             "inventory_id" => 14_323_335,
             "quantity" => 0,
             "original_quantity" => 1,
             "merchant_id" => 1007,
             "name" => "MODULES",
             "price" => nil,
             "image" => "/images/product-placeholder.png",
             "way_point_id" => 11_061_564,
             "scan_string" => "1591098207",
             "pending" => true,
             "note" => "Other",
             "parent_task_inventory_id" => nil,
             "coc_type" => nil,
             "external_id" => "14323335",
             "size" => nil,
             "weight" => 450.0,
             "length" => nil,
             "height" => nil,
             "width" => nil,
             "source_task_id" => nil,
             "rejected_quantity" => 0,
             "assigned_serial" => nil,
             "actions_configuration_id" => nil,
             "scheduled_arrival" => nil,
             "inventory" => %{
               "id" => 14_323_335,
               "name" => "MODULES",
               "price" => 20,
               "image" => "/images/product-placeholder.png",
               "merchant_id" => 1007,
               "external_id" => "14323335",
               "scan_string" => "1591098207",
               "commodity" => nil,
               "notes" => nil,
               "weight" => 450.0,
               "size" => nil,
               "extras" => nil,
               "delivery_cost" => nil,
               "completed" => nil,
               "width" => nil,
               "height" => nil,
               "length" => nil,
               "volume" => nil,
               "description" => nil,
               "limitations" => nil,
               "age_restricted" => nil
             }
           }
         ],
         "scans" => [],
         "invalid_reasons" => [],
         "service_plan" => nil
       }
     }}
  end

  def cancel_order(_, payload) do
    PubSub.broadcast!(FraytElixir.PubSub, "fake_bringg", {:bringg_cancel, payload})

    {:ok,
     %{
       "success" => true,
       "task" => %{
         "title" => "1591098207",
         "user_id" => 669_602,
         "created_at" => "2020-06-02T11:43:28.866Z",
         "scheduled_at" => nil,
         "lat" => 35.6961331,
         "lng" => -78.6922998,
         "status" => 7,
         "id" => 7_188_943,
         "address" => "6305 LAKE WHEELER RD",
         "active_way_point_id" => 11_061_565,
         "started_time" => "2020-06-03T16:59:43.351Z",
         "cancelled_at" => nil,
         "cancellation_lat" => nil,
         "cancellation_lng" => nil,
         "late" => false,
         "extras" => %{
           "integration" => %{
             "trackingNumber" => "1591098207",
             "uniqueIdentifier" => "ABC"
           }
         },
         "external_id" => "1591098207-R0",
         "customer_id" => 7_199_889,
         "asap" => nil,
         "ended_time" => nil,
         "priority" => 7_188_943,
         "distance_traveled" => nil,
         "total_price" => nil,
         "delivery_cost" => nil,
         "delivery_price" => nil,
         "tip" => nil,
         "pre_delivery_tip" => nil,
         "post_delivery_tip_cash" => nil,
         "post_delivery_tip_credit" => nil,
         "left_to_be_paid" => nil,
         "task_cancellation_reason" => payload.reason,
         "dispatcher_id" => nil,
         "uuid" => "c3952fcd-80ba-4e31-b1cd-bf861e2b0503",
         "ready_to_execute" => true,
         "discount" => nil,
         "tip_driver_enabled" => false,
         "tax_price" => nil,
         "price_before_tax" => nil,
         "tag_id" => 588,
         "group_uuid" => nil,
         "group_leader_id" => nil,
         "automatically_cancelled" => 0,
         "parent_task_id" => nil,
         "payment_method" => nil,
         "payment_type_name" => nil,
         "linked_task_id" => nil,
         "preparation_status" => 0,
         "preparation_start_time_planned" => nil,
         "preparation_end_time_planned" => nil,
         "preparation_ready_for_pickup_time_planned" => nil,
         "invalidated" => false,
         "automatically_assigned" => true,
         "task_type_id" => 4,
         "origin_title" => "Service",
         "task_configuration_id" => nil,
         "required_skills" => [],
         "team_ids" => [
           77910
         ],
         "virtual_task" => false,
         "run_id" => 3_491_474,
         "fleet_id" => 180,
         "preparation_external_id" => nil,
         "rank" => nil,
         "fleet_delivery_external_id" => "123",
         "task_notes" => [],
         "way_points" => [
           %{
             "id" => 11_061_564,
             "scheduled_at" => nil,
             "has_to_leave_by" => nil,
             "task_id" => 7_188_943,
             "customer_id" => 7_199_890,
             "done" => true,
             "lat" => 35.7686299,
             "lng" => -78.5487832,
             "address" => "5210 TRADEMARK DRIVE, RALEIGH, NC",
             "address_second_line" => nil,
             "zipcode" => "27610",
             "position" => 1,
             "checkin_time" => "2020-06-03T17:15:29.697Z",
             "checkout_time" => "2020-06-03T17:21:05.987Z",
             "note" => nil,
             "find_me" => nil,
             "asap" => nil,
             "late" => false,
             "etl" => "2020-06-03T17:21:05.987Z",
             "eta" => nil,
             "silent" => false,
             "city" => "Raleigh",
             "borough" => nil,
             "full_address" => "5210 TRADEMARK DRIVE, RALEIGH, NC, Raleigh, 27610",
             "automatic_checkin" => false,
             "automatic_checkout" => false,
             "phone" => nil,
             "email" => nil,
             "no_later_than" => nil,
             "no_earlier_than" => nil,
             "rating" => nil,
             "checkin_lat" => nil,
             "checkin_lng" => nil,
             "checkout_lat" => nil,
             "checkout_lng" => nil,
             "district" => nil,
             "house_number" => nil,
             "company_name" => nil,
             "pickup_dropoff_option" => 0,
             "etos" => 300,
             "address_type" => nil,
             "location_name" => nil,
             "scheduled_arrival" => nil,
             "name" => "Warehouse",
             "ui_data" => nil,
             "customer" => %{
               "id" => 7_199_890,
               "name" => "Warehouse",
               "address" => nil,
               "lat" => nil,
               "lng" => nil,
               "created_at" => "2020-06-02T11:43:28.443Z",
               "updated_at" => "2020-06-03T17:15:29.938Z",
               "phone" => nil,
               "merchant_id" => 1007,
               "image" => nil,
               "access_token" => "e9e6cc96-d195-4b6a-a14b-767f40266880",
               "confirmation_code" => "1078",
               "salt" => nil,
               "approved" => false,
               "push_token" => nil,
               "uuid" => "4dfac88e-2ae2-4c38-95ee-edebde81746d",
               "email" => nil,
               "external_id" => "7199890",
               "delete_at" => nil,
               "facebook_id" => nil,
               "extras" => nil,
               "original_lat_lng_changed" => nil,
               "encrypted_password" => "",
               "blocked_email" => false,
               "address_second_line" => nil,
               "zipcode" => nil,
               "allow_login" => false,
               "stripe_id" => nil,
               "original_phone_number" => nil,
               "last_open_at" => nil,
               "last_order_at" => nil,
               "uploaded_profile_image" => %{
                 "url" => "/images/avatar.png"
               },
               "original_lat" => nil,
               "original_lng" => nil,
               "consecutive_checkins_out_of_geofence" => 0,
               "allow_sending_email" => true,
               "allow_sending_sms" => true,
               "reset_password_token" => nil,
               "reset_password_sent_at" => nil,
               "mobile_version" => nil,
               "mobile_type" => 0,
               "mobile_maker" => nil,
               "client_version" => nil,
               "client_name" => nil,
               "city" => nil,
               "borough" => nil,
               "state" => nil,
               "dev" => false,
               "business_code" => nil,
               "language" => nil,
               "district" => nil,
               "house_number" => nil,
               "street" => nil,
               "allow_dynamically_updating_location" => nil,
               "is_sales_rep" => false,
               "address_type" => nil,
               "tax_payer_external_id" => nil,
               "tax_payer_name" => nil,
               "rank" => nil,
               "user_id" => nil
             }
           },
           %{
             "id" => 11_061_565,
             "scheduled_at" => nil,
             "has_to_leave_by" => nil,
             "task_id" => 7_188_943,
             "customer_id" => 7_199_049,
             "done" => false,
             "lat" => 35.6961331,
             "lng" => -78.6922998,
             "address" => "6305 LAKE WHEELER RD",
             "address_second_line" => nil,
             "zipcode" => "27603",
             "position" => 2,
             "checkin_time" => nil,
             "checkout_time" => nil,
             "note" => nil,
             "find_me" => nil,
             "asap" => nil,
             "late" => false,
             "etl" => "2020-06-03T17:23:57.866Z",
             "eta" => "2020-06-03T17:18:57.866Z",
             "silent" => false,
             "city" => "RALEIGH",
             "borough" => nil,
             "full_address" => "6305 LAKE WHEELER RD, RALEIGH, NC, 27603",
             "automatic_checkin" => false,
             "automatic_checkout" => false,
             "phone" => "+15555555555",
             "email" => "",
             "no_later_than" => nil,
             "no_earlier_than" => nil,
             "rating" => nil,
             "checkin_lat" => nil,
             "checkin_lng" => nil,
             "checkout_lat" => nil,
             "checkout_lng" => nil,
             "district" => nil,
             "house_number" => nil,
             "company_name" => nil,
             "pickup_dropoff_option" => 1,
             "etos" => 300,
             "address_type" => nil,
             "location_name" => nil,
             "scheduled_arrival" => nil,
             "name" => "DO SUPPLY INC",
             "ui_data" => nil,
             "customer" => %{
               "id" => 7_199_049,
               "name" => "John Smith",
               "address" => nil,
               "lat" => nil,
               "lng" => nil,
               "created_at" => "2020-06-02T08:01:47.114Z",
               "updated_at" => "2020-06-02T08:47:06.584Z",
               "phone" => "+15555555555",
               "merchant_id" => 1007,
               "image" => nil,
               "access_token" => "767305d7-4eac-43fb-b731-6028f9f1d41b",
               "confirmation_code" => "1543",
               "salt" => nil,
               "approved" => false,
               "push_token" => nil,
               "uuid" => "0846443f-abcf-4a36-b033-387da774be06",
               "email" => "",
               "external_id" => "7199049",
               "delete_at" => nil,
               "facebook_id" => nil,
               "extras" => nil,
               "original_lat_lng_changed" => nil,
               "encrypted_password" => "",
               "blocked_email" => false,
               "address_second_line" => nil,
               "zipcode" => nil,
               "allow_login" => false,
               "stripe_id" => nil,
               "original_phone_number" => "+15555555555",
               "last_open_at" => nil,
               "last_order_at" => nil,
               "uploaded_profile_image" => %{
                 "url" => "/images/avatar.png"
               },
               "original_lat" => nil,
               "original_lng" => nil,
               "consecutive_checkins_out_of_geofence" => 0,
               "allow_sending_email" => true,
               "allow_sending_sms" => true,
               "reset_password_token" => nil,
               "reset_password_sent_at" => nil,
               "mobile_version" => nil,
               "mobile_type" => 0,
               "mobile_maker" => nil,
               "client_version" => nil,
               "client_name" => nil,
               "city" => nil,
               "borough" => nil,
               "state" => nil,
               "dev" => false,
               "business_code" => nil,
               "language" => nil,
               "district" => nil,
               "house_number" => nil,
               "street" => nil,
               "allow_dynamically_updating_location" => nil,
               "is_sales_rep" => false,
               "address_type" => nil,
               "tax_payer_external_id" => nil,
               "tax_payer_name" => nil,
               "rank" => nil,
               "user_id" => nil
             }
           }
         ],
         "shared_locations" => [
           %{
             "id" => 7_994_142,
             "url" => "https://app.bringg.com/sen.html?e8oPy81V&e=6",
             "expired" => false,
             "way_point_id" => 11_061_565,
             "customer_id" => 7_199_049,
             "first_seen_on" => nil,
             "failure_reason" => nil,
             "shared_successfully" => true,
             "shared_on" => "2020-06-03T17:21:07.169Z",
             "view_counter" => 0,
             "uuid" => "e8oPy81V",
             "sharing_method" => 0,
             "shared_type" => 1,
             "was_forwarded" => false
           }
         ],
         "task_inventories" => [
           %{
             "id" => 29_417_962,
             "task_id" => 7_188_943,
             "inventory_id" => 14_323_336,
             "quantity" => 0,
             "original_quantity" => 1,
             "merchant_id" => 1007,
             "name" => "MODULES",
             "price" => nil,
             "image" => "/images/product-placeholder.png",
             "way_point_id" => 11_061_565,
             "scan_string" => "1591098207",
             "pending" => false,
             "note" => "Other",
             "parent_task_inventory_id" => nil,
             "coc_type" => nil,
             "external_id" => "14323336",
             "size" => nil,
             "weight" => 450.0,
             "length" => nil,
             "height" => nil,
             "width" => nil,
             "source_task_id" => nil,
             "rejected_quantity" => 0,
             "assigned_serial" => nil,
             "actions_configuration_id" => nil,
             "scheduled_arrival" => nil,
             "inventory" => %{
               "id" => 14_323_336,
               "name" => "MODULES",
               "price" => 20,
               "image" => "/images/product-placeholder.png",
               "merchant_id" => 1007,
               "external_id" => "14323336",
               "scan_string" => "1591098207",
               "commodity" => nil,
               "notes" => nil,
               "weight" => 450.0,
               "size" => nil,
               "extras" => nil,
               "delivery_cost" => nil,
               "completed" => nil,
               "width" => nil,
               "height" => nil,
               "length" => nil,
               "volume" => nil,
               "description" => nil,
               "limitations" => nil,
               "age_restricted" => nil
             }
           },
           %{
             "id" => 29_417_961,
             "task_id" => 7_188_943,
             "inventory_id" => 14_323_335,
             "quantity" => 0,
             "original_quantity" => 1,
             "merchant_id" => 1007,
             "name" => "MODULES",
             "price" => nil,
             "image" => "/images/product-placeholder.png",
             "way_point_id" => 11_061_564,
             "scan_string" => "1591098207",
             "pending" => true,
             "note" => "Other",
             "parent_task_inventory_id" => nil,
             "coc_type" => nil,
             "external_id" => "14323335",
             "size" => nil,
             "weight" => 450.0,
             "length" => nil,
             "height" => nil,
             "width" => nil,
             "source_task_id" => nil,
             "rejected_quantity" => 0,
             "assigned_serial" => nil,
             "actions_configuration_id" => nil,
             "scheduled_arrival" => nil,
             "inventory" => %{
               "id" => 14_323_335,
               "name" => "MODULES",
               "price" => 20,
               "image" => "/images/product-placeholder.png",
               "merchant_id" => 1007,
               "external_id" => "14323335",
               "scan_string" => "1591098207",
               "commodity" => nil,
               "notes" => nil,
               "weight" => 450.0,
               "size" => nil,
               "extras" => nil,
               "delivery_cost" => nil,
               "completed" => nil,
               "width" => nil,
               "height" => nil,
               "length" => nil,
               "volume" => nil,
               "description" => nil,
               "limitations" => nil,
               "age_restricted" => nil
             }
           }
         ],
         "scans" => [],
         "invalid_reasons" => [],
         "service_plan" => nil
       }
     }}
  end

  def get_token(_) do
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdXQiOiJvYXV0aDIiLCJqdGkiOiIwNDFjMzY5NTg2NTkyYmU1MDc3NjBiYTJhNDJhYjg3ZCIsInN1YiI6IlVzZXI6MTM5Nzc3NyIsInRpZCI6Ik1lcmNoYW50OjEzMjAiLCJpYXQiOjE2MDAzNzI1NjQsImV4cCI6MTYwMDM3NDM2NCwic2xpIjowLCJhdWQiOiI2VGpSdUdiek1NWUFSbGxaV3JJV3pZM2MwN2lSNDlfRlVMX3lfYWJWbElFIiwiaXNzIjoidXJuOngtYnJpbmdnOnNlcnZpY2U6YXBpIiwicmVnIjoidXMtZWFzdC00LWdjcCIsInNjcCI6WyJmbGVldCJdLCJ2ZXIiOiIyLjAifQ.GFExIvxE3mTKtG0gjEe4KVS6HDqHiRewPp_6sAgxcRXEAifHHKVwr6YTeS7FpoKYuIr5sEYV9ew9OBzhfBmtnQ"
    # {:ok,
    #  %HTTPoison.Response{
    #    body: "{
    #      \"access_token\":
    #        \"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdXQiOiJvYXV0aDIiLCJqdGkiOiIwNDFjMzY5NTg2NTkyYmU1MDc3NjBiYTJhNDJhYjg3ZCIsInN1YiI6IlVzZXI6MTM5Nzc3NyIsInRpZCI6Ik1lcmNoYW50OjEzMjAiLCJpYXQiOjE2MDAzNzI1NjQsImV4cCI6MTYwMDM3NDM2NCwic2xpIjowLCJhdWQiOiI2VGpSdUdiek1NWUFSbGxaV3JJV3pZM2MwN2lSNDlfRlVMX3lfYWJWbElFIiwiaXNzIjoidXJuOngtYnJpbmdnOnNlcnZpY2U6YXBpIiwicmVnIjoidXMtZWFzdC00LWdjcCIsInNjcCI6WyJmbGVldCJdLCJ2ZXIiOiIyLjAifQ.GFExIvxE3mTKtG0gjEe4KVS6HDqHiRewPp_6sAgxcRXEAifHHKVwr6YTeS7FpoKYuIr5sEYV9ew9OBzhfBmtnQ\",
    #      \"created_at\": 1_600_372_564,
    #      \"expires_in\": 1800,
    #      \"token_type\": \"Bearer\"
    #    }"
    #  }}
  end
end
